/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface AdminSummary {
    pending: number;
    approvedToday: number;
    upcoming: number;
    reports: number;
}
//# sourceMappingURL=adminSummary.d.ts.map