/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List public Bhandaras
 */
export declare const listBhandarasQueryQMax = 120;
export declare const listBhandarasQueryCityMax = 80;
export declare const listBhandarasQueryLocalityMax = 80;
export declare const listBhandarasQueryDateFilterDefault = "all";
export declare const listBhandarasQueryMaxDistanceKmMax = 200;
export declare const listBhandarasQueryLatitudeMin = -90;
export declare const listBhandarasQueryLatitudeMax = 90;
export declare const listBhandarasQueryLongitudeMin = -180;
export declare const listBhandarasQueryLongitudeMax = 180;
export declare const listBhandarasQuerySortDefault = "soonest";
export declare const listBhandarasQueryLimitDefault = 50;
export declare const listBhandarasQueryLimitMax = 100;
export declare const ListBhandarasQueryParams: zod.ZodObject<{
    q: zod.ZodOptional<zod.ZodString>;
    city: zod.ZodOptional<zod.ZodString>;
    locality: zod.ZodOptional<zod.ZodString>;
    dateFilter: zod.ZodDefault<zod.ZodEnum<["all", "today", "tomorrow", "week", "custom"]>>;
    date: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    maxDistanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    latitude: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    longitude: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    sort: zod.ZodDefault<zod.ZodEnum<["soonest", "nearest"]>>;
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    sort: "soonest" | "nearest";
    dateFilter: "all" | "today" | "tomorrow" | "week" | "custom";
    limit: number;
    q?: string | undefined;
    city?: string | undefined;
    locality?: string | undefined;
    date?: Date | null | undefined;
    maxDistanceKm?: number | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
}, {
    sort?: "soonest" | "nearest" | undefined;
    q?: string | undefined;
    city?: string | undefined;
    locality?: string | undefined;
    dateFilter?: "all" | "today" | "tomorrow" | "week" | "custom" | undefined;
    date?: Date | null | undefined;
    maxDistanceKm?: number | null | undefined;
    latitude?: number | null | undefined;
    longitude?: number | null | undefined;
    limit?: number | undefined;
}>;
export declare const ListBhandarasResponse: zod.ZodObject<{
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        temple: zod.ZodString;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        locality: zod.ZodString;
        city: zod.ZodString;
        address: zod.ZodString;
        startAt: zod.ZodDate;
        endAt: zod.ZodDate;
        prasad: zod.ZodString;
        organizerName: zod.ZodOptional<zod.ZodString>;
        organizerPhone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        latitude: zod.ZodNumber;
        longitude: zod.ZodNumber;
        distanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        verificationStatus: zod.ZodEnum<["pending", "approved", "rejected"]>;
        verificationNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isFeatured: zod.ZodBoolean;
        favoriteCount: zod.ZodOptional<zod.ZodNumber>;
        createdAt: zod.ZodDate;
        updatedAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }, {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }>, "many">;
    total: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    items: {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }[];
    total: number;
}, {
    items: {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Submit a Bhandara for review
 */
export declare const submitBhandaraBodyNameMin = 2;
export declare const submitBhandaraBodyNameMax = 120;
export declare const submitBhandaraBodyTempleMin = 2;
export declare const submitBhandaraBodyTempleMax = 120;
export declare const submitBhandaraBodyDescriptionMax = 500;
export declare const submitBhandaraBodyLocalityMin = 2;
export declare const submitBhandaraBodyLocalityMax = 80;
export declare const submitBhandaraBodyCityMin = 2;
export declare const submitBhandaraBodyCityMax = 80;
export declare const submitBhandaraBodyAddressMin = 5;
export declare const submitBhandaraBodyAddressMax = 240;
export declare const submitBhandaraBodyPrasadMin = 2;
export declare const submitBhandaraBodyPrasadMax = 120;
export declare const submitBhandaraBodyOrganizerNameMin = 2;
export declare const submitBhandaraBodyOrganizerNameMax = 120;
export declare const submitBhandaraBodyOrganizerPhoneMax = 30;
export declare const submitBhandaraBodyLatitudeMin = -90;
export declare const submitBhandaraBodyLatitudeMax = 90;
export declare const submitBhandaraBodyLongitudeMin = -180;
export declare const submitBhandaraBodyLongitudeMax = 180;
export declare const SubmitBhandaraBody: zod.ZodObject<{
    name: zod.ZodString;
    temple: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    locality: zod.ZodString;
    city: zod.ZodString;
    address: zod.ZodString;
    startAt: zod.ZodDate;
    endAt: zod.ZodDate;
    prasad: zod.ZodString;
    organizerName: zod.ZodString;
    organizerPhone: zod.ZodOptional<zod.ZodString>;
    latitude: zod.ZodNumber;
    longitude: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    organizerName: string;
    description?: string | undefined;
    organizerPhone?: string | undefined;
}, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    organizerName: string;
    description?: string | undefined;
    organizerPhone?: string | undefined;
}>;
export declare const SubmitBhandaraResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    temple: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    locality: zod.ZodString;
    city: zod.ZodString;
    address: zod.ZodString;
    startAt: zod.ZodDate;
    endAt: zod.ZodDate;
    prasad: zod.ZodString;
    organizerName: zod.ZodOptional<zod.ZodString>;
    organizerPhone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    latitude: zod.ZodNumber;
    longitude: zod.ZodNumber;
    distanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    verificationStatus: zod.ZodEnum<["pending", "approved", "rejected"]>;
    verificationNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isFeatured: zod.ZodBoolean;
    favoriteCount: zod.ZodOptional<zod.ZodNumber>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}>;
/**
 * @summary Get a public Bhandara
 */
export declare const GetBhandaraParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetBhandaraResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    temple: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    locality: zod.ZodString;
    city: zod.ZodString;
    address: zod.ZodString;
    startAt: zod.ZodDate;
    endAt: zod.ZodDate;
    prasad: zod.ZodString;
    organizerName: zod.ZodOptional<zod.ZodString>;
    organizerPhone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    latitude: zod.ZodNumber;
    longitude: zod.ZodNumber;
    distanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    verificationStatus: zod.ZodEnum<["pending", "approved", "rejected"]>;
    verificationNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isFeatured: zod.ZodBoolean;
    favoriteCount: zod.ZodOptional<zod.ZodNumber>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}>;
/**
 * @summary Update a submitted Bhandara
 */
export declare const UpdateBhandaraParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const updateBhandaraBodyOneNameMin = 2;
export declare const updateBhandaraBodyOneNameMax = 120;
export declare const updateBhandaraBodyOneTempleMin = 2;
export declare const updateBhandaraBodyOneTempleMax = 120;
export declare const updateBhandaraBodyOneDescriptionMax = 500;
export declare const updateBhandaraBodyOneLocalityMin = 2;
export declare const updateBhandaraBodyOneLocalityMax = 80;
export declare const updateBhandaraBodyOneCityMin = 2;
export declare const updateBhandaraBodyOneCityMax = 80;
export declare const updateBhandaraBodyOneAddressMin = 5;
export declare const updateBhandaraBodyOneAddressMax = 240;
export declare const updateBhandaraBodyOnePrasadMin = 2;
export declare const updateBhandaraBodyOnePrasadMax = 120;
export declare const updateBhandaraBodyOneOrganizerNameMin = 2;
export declare const updateBhandaraBodyOneOrganizerNameMax = 120;
export declare const updateBhandaraBodyOneOrganizerPhoneMax = 30;
export declare const updateBhandaraBodyOneLatitudeMin = -90;
export declare const updateBhandaraBodyOneLatitudeMax = 90;
export declare const updateBhandaraBodyOneLongitudeMin = -180;
export declare const updateBhandaraBodyOneLongitudeMax = 180;
export declare const UpdateBhandaraBody: zod.ZodObject<{
    name: zod.ZodString;
    temple: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    locality: zod.ZodString;
    city: zod.ZodString;
    address: zod.ZodString;
    startAt: zod.ZodDate;
    endAt: zod.ZodDate;
    prasad: zod.ZodString;
    organizerName: zod.ZodString;
    organizerPhone: zod.ZodOptional<zod.ZodString>;
    latitude: zod.ZodNumber;
    longitude: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    organizerName: string;
    description?: string | undefined;
    organizerPhone?: string | undefined;
}, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    organizerName: string;
    description?: string | undefined;
    organizerPhone?: string | undefined;
}>;
export declare const UpdateBhandaraResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    temple: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    locality: zod.ZodString;
    city: zod.ZodString;
    address: zod.ZodString;
    startAt: zod.ZodDate;
    endAt: zod.ZodDate;
    prasad: zod.ZodString;
    organizerName: zod.ZodOptional<zod.ZodString>;
    organizerPhone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    latitude: zod.ZodNumber;
    longitude: zod.ZodNumber;
    distanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    verificationStatus: zod.ZodEnum<["pending", "approved", "rejected"]>;
    verificationNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isFeatured: zod.ZodBoolean;
    favoriteCount: zod.ZodOptional<zod.ZodNumber>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}>;
/**
 * @summary Save a Bhandara for a device or signed-in user
 */
export declare const FavoriteBhandaraParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const favoriteBhandaraBodyUserKeyMax = 160;
export declare const FavoriteBhandaraBody: zod.ZodObject<{
    userKey: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    userKey: string;
}, {
    userKey: string;
}>;
export declare const FavoriteBhandaraResponse: zod.ZodObject<{
    favorited: zod.ZodBoolean;
    favoriteCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    favoriteCount: number;
    favorited: boolean;
}, {
    favoriteCount: number;
    favorited: boolean;
}>;
/**
 * @summary Remove a saved Bhandara
 */
export declare const UnfavoriteBhandaraParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const unfavoriteBhandaraBodyUserKeyMax = 160;
export declare const UnfavoriteBhandaraBody: zod.ZodObject<{
    userKey: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    userKey: string;
}, {
    userKey: string;
}>;
export declare const UnfavoriteBhandaraResponse: zod.ZodObject<{
    favorited: zod.ZodBoolean;
    favoriteCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    favoriteCount: number;
    favorited: boolean;
}, {
    favoriteCount: number;
    favorited: boolean;
}>;
/**
 * @summary Report an incorrect, cancelled, or duplicate Bhandara
 */
export declare const reportBhandaraBodyNoteMax = 500;
export declare const reportBhandaraBodyReporterKeyMax = 160;
export declare const ReportBhandaraBody: zod.ZodObject<{
    bhandaraId: zod.ZodNumber;
    reason: zod.ZodEnum<["incorrect", "cancelled", "duplicate", "other"]>;
    note: zod.ZodOptional<zod.ZodString>;
    reporterKey: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    bhandaraId: number;
    reason: "incorrect" | "cancelled" | "duplicate" | "other";
    note?: string | undefined;
    reporterKey?: string | undefined;
}, {
    bhandaraId: number;
    reason: "incorrect" | "cancelled" | "duplicate" | "other";
    note?: string | undefined;
    reporterKey?: string | undefined;
}>;
export declare const ReportBhandaraResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    bhandaraId: zod.ZodNumber;
    reason: zod.ZodString;
    note: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["open", "reviewed", "dismissed"]>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "open" | "reviewed" | "dismissed";
    id: number;
    createdAt: Date;
    bhandaraId: number;
    reason: string;
    note?: string | null | undefined;
}, {
    status: "open" | "reviewed" | "dismissed";
    id: number;
    createdAt: Date;
    bhandaraId: number;
    reason: string;
    note?: string | null | undefined;
}>;
/**
 * @summary Get moderation summary
 */
export declare const GetAdminSummaryResponse: zod.ZodObject<{
    pending: zod.ZodNumber;
    approvedToday: zod.ZodNumber;
    upcoming: zod.ZodNumber;
    reports: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    pending: number;
    approvedToday: number;
    upcoming: number;
    reports: number;
}, {
    pending: number;
    approvedToday: number;
    upcoming: number;
    reports: number;
}>;
/**
 * @summary List submissions for moderation
 */
export declare const listAdminBhandarasQueryStatusDefault = "pending";
export declare const listAdminBhandarasQueryQMax = 120;
export declare const ListAdminBhandarasQueryParams: zod.ZodObject<{
    status: zod.ZodDefault<zod.ZodEnum<["pending", "approved", "rejected", "all"]>>;
    q: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "all" | "pending" | "approved" | "rejected";
    q?: string | undefined;
}, {
    status?: "all" | "pending" | "approved" | "rejected" | undefined;
    q?: string | undefined;
}>;
export declare const ListAdminBhandarasResponse: zod.ZodObject<{
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        temple: zod.ZodString;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        locality: zod.ZodString;
        city: zod.ZodString;
        address: zod.ZodString;
        startAt: zod.ZodDate;
        endAt: zod.ZodDate;
        prasad: zod.ZodString;
        organizerName: zod.ZodOptional<zod.ZodString>;
        organizerPhone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        latitude: zod.ZodNumber;
        longitude: zod.ZodNumber;
        distanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        verificationStatus: zod.ZodEnum<["pending", "approved", "rejected"]>;
        verificationNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isFeatured: zod.ZodBoolean;
        favoriteCount: zod.ZodOptional<zod.ZodNumber>;
        createdAt: zod.ZodDate;
        updatedAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }, {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }>, "many">;
    total: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    items: {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }[];
    total: number;
}, {
    items: {
        city: string;
        locality: string;
        latitude: number;
        longitude: number;
        id: number;
        name: string;
        temple: string;
        address: string;
        startAt: Date;
        endAt: Date;
        prasad: string;
        verificationStatus: "pending" | "approved" | "rejected";
        isFeatured: boolean;
        createdAt: Date;
        updatedAt: Date;
        description?: string | null | undefined;
        organizerName?: string | undefined;
        organizerPhone?: string | null | undefined;
        distanceKm?: number | null | undefined;
        verificationNote?: string | null | undefined;
        favoriteCount?: number | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Approve, edit, or reject a submission
 */
export declare const ModerateBhandaraParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const moderateBhandaraBodyVerificationNoteMax = 500;
export declare const moderateBhandaraBodyNameMax = 120;
export declare const moderateBhandaraBodyPrasadMax = 120;
export declare const moderateBhandaraBodyAddressMax = 240;
export declare const ModerateBhandaraBody: zod.ZodObject<{
    action: zod.ZodEnum<["approve", "reject", "edit"]>;
    verificationNote: zod.ZodOptional<zod.ZodString>;
    name: zod.ZodOptional<zod.ZodString>;
    startAt: zod.ZodOptional<zod.ZodDate>;
    endAt: zod.ZodOptional<zod.ZodDate>;
    prasad: zod.ZodOptional<zod.ZodString>;
    address: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    action: "approve" | "reject" | "edit";
    name?: string | undefined;
    address?: string | undefined;
    startAt?: Date | undefined;
    endAt?: Date | undefined;
    prasad?: string | undefined;
    verificationNote?: string | undefined;
}, {
    action: "approve" | "reject" | "edit";
    name?: string | undefined;
    address?: string | undefined;
    startAt?: Date | undefined;
    endAt?: Date | undefined;
    prasad?: string | undefined;
    verificationNote?: string | undefined;
}>;
export declare const ModerateBhandaraResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    temple: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    locality: zod.ZodString;
    city: zod.ZodString;
    address: zod.ZodString;
    startAt: zod.ZodDate;
    endAt: zod.ZodDate;
    prasad: zod.ZodString;
    organizerName: zod.ZodOptional<zod.ZodString>;
    organizerPhone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    latitude: zod.ZodNumber;
    longitude: zod.ZodNumber;
    distanceKm: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    verificationStatus: zod.ZodEnum<["pending", "approved", "rejected"]>;
    verificationNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isFeatured: zod.ZodBoolean;
    favoriteCount: zod.ZodOptional<zod.ZodNumber>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}, {
    city: string;
    locality: string;
    latitude: number;
    longitude: number;
    id: number;
    name: string;
    temple: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    verificationStatus: "pending" | "approved" | "rejected";
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    description?: string | null | undefined;
    organizerName?: string | undefined;
    organizerPhone?: string | null | undefined;
    distanceKm?: number | null | undefined;
    verificationNote?: string | null | undefined;
    favoriteCount?: number | undefined;
}>;
/**
 * @summary Delete a Bhandara
 */
export declare const DeleteBhandaraParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteBhandaraResponse: zod.ZodVoid;
//# sourceMappingURL=api.d.ts.map