/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List public Bhandaras
 */
export const listBhandarasQueryQMax = 120;

export const listBhandarasQueryCityMax = 80;

export const listBhandarasQueryLocalityMax = 80;

export const listBhandarasQueryDateFilterDefault = `all`;
export const listBhandarasQueryMaxDistanceKmMax = 200;

export const listBhandarasQueryLatitudeMin = -90;
export const listBhandarasQueryLatitudeMax = 90;

export const listBhandarasQueryLongitudeMin = -180;
export const listBhandarasQueryLongitudeMax = 180;

export const listBhandarasQuerySortDefault = `soonest`;
export const listBhandarasQueryLimitDefault = 50;
export const listBhandarasQueryLimitMax = 100;



export const ListBhandarasQueryParams = zod.object({
  "q": zod.coerce.string().max(listBhandarasQueryQMax).optional(),
  "city": zod.coerce.string().max(listBhandarasQueryCityMax).optional(),
  "locality": zod.coerce.string().max(listBhandarasQueryLocalityMax).optional(),
  "dateFilter": zod.enum(['all', 'today', 'tomorrow', 'week', 'custom']).default(listBhandarasQueryDateFilterDefault),
  "date": zod.date().nullish(),
  "maxDistanceKm": zod.coerce.number().min(1).max(listBhandarasQueryMaxDistanceKmMax).nullish(),
  "latitude": zod.coerce.number().min(listBhandarasQueryLatitudeMin).max(listBhandarasQueryLatitudeMax).nullish(),
  "longitude": zod.coerce.number().min(listBhandarasQueryLongitudeMin).max(listBhandarasQueryLongitudeMax).nullish(),
  "sort": zod.enum(['soonest', 'nearest']).default(listBhandarasQuerySortDefault),
  "limit": zod.coerce.number().int().min(1).max(listBhandarasQueryLimitMax).default(listBhandarasQueryLimitDefault)
})

export const ListBhandarasResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "temple": zod.string(),
  "description": zod.string().nullish(),
  "locality": zod.string(),
  "city": zod.string(),
  "address": zod.string(),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string(),
  "organizerName": zod.string().optional(),
  "organizerPhone": zod.string().nullish(),
  "latitude": zod.number(),
  "longitude": zod.number(),
  "distanceKm": zod.number().nullish(),
  "verificationStatus": zod.enum(['pending', 'approved', 'rejected']),
  "verificationNote": zod.string().nullish(),
  "isFeatured": zod.boolean(),
  "favoriteCount": zod.number().int().optional(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})),
  "total": zod.number().int()
})


/**
 * @summary Submit a Bhandara for review
 */
export const submitBhandaraBodyNameMin = 2;
export const submitBhandaraBodyNameMax = 120;

export const submitBhandaraBodyTempleMin = 2;
export const submitBhandaraBodyTempleMax = 120;

export const submitBhandaraBodyDescriptionMax = 500;

export const submitBhandaraBodyLocalityMin = 2;
export const submitBhandaraBodyLocalityMax = 80;

export const submitBhandaraBodyCityMin = 2;
export const submitBhandaraBodyCityMax = 80;

export const submitBhandaraBodyAddressMin = 5;
export const submitBhandaraBodyAddressMax = 240;

export const submitBhandaraBodyPrasadMin = 2;
export const submitBhandaraBodyPrasadMax = 120;

export const submitBhandaraBodyOrganizerNameMin = 2;
export const submitBhandaraBodyOrganizerNameMax = 120;

export const submitBhandaraBodyOrganizerPhoneMax = 30;

export const submitBhandaraBodyLatitudeMin = -90;
export const submitBhandaraBodyLatitudeMax = 90;

export const submitBhandaraBodyLongitudeMin = -180;
export const submitBhandaraBodyLongitudeMax = 180;



export const SubmitBhandaraBody = zod.object({
  "name": zod.string().min(submitBhandaraBodyNameMin).max(submitBhandaraBodyNameMax),
  "temple": zod.string().min(submitBhandaraBodyTempleMin).max(submitBhandaraBodyTempleMax),
  "description": zod.string().max(submitBhandaraBodyDescriptionMax).optional(),
  "locality": zod.string().min(submitBhandaraBodyLocalityMin).max(submitBhandaraBodyLocalityMax),
  "city": zod.string().min(submitBhandaraBodyCityMin).max(submitBhandaraBodyCityMax),
  "address": zod.string().min(submitBhandaraBodyAddressMin).max(submitBhandaraBodyAddressMax),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string().min(submitBhandaraBodyPrasadMin).max(submitBhandaraBodyPrasadMax),
  "organizerName": zod.string().min(submitBhandaraBodyOrganizerNameMin).max(submitBhandaraBodyOrganizerNameMax),
  "organizerPhone": zod.string().max(submitBhandaraBodyOrganizerPhoneMax).optional(),
  "latitude": zod.number().min(submitBhandaraBodyLatitudeMin).max(submitBhandaraBodyLatitudeMax),
  "longitude": zod.number().min(submitBhandaraBodyLongitudeMin).max(submitBhandaraBodyLongitudeMax)
})

export const SubmitBhandaraResponse = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "temple": zod.string(),
  "description": zod.string().nullish(),
  "locality": zod.string(),
  "city": zod.string(),
  "address": zod.string(),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string(),
  "organizerName": zod.string().optional(),
  "organizerPhone": zod.string().nullish(),
  "latitude": zod.number(),
  "longitude": zod.number(),
  "distanceKm": zod.number().nullish(),
  "verificationStatus": zod.enum(['pending', 'approved', 'rejected']),
  "verificationNote": zod.string().nullish(),
  "isFeatured": zod.boolean(),
  "favoriteCount": zod.number().int().optional(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Get a public Bhandara
 */



export const GetBhandaraParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const GetBhandaraResponse = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "temple": zod.string(),
  "description": zod.string().nullish(),
  "locality": zod.string(),
  "city": zod.string(),
  "address": zod.string(),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string(),
  "organizerName": zod.string().optional(),
  "organizerPhone": zod.string().nullish(),
  "latitude": zod.number(),
  "longitude": zod.number(),
  "distanceKm": zod.number().nullish(),
  "verificationStatus": zod.enum(['pending', 'approved', 'rejected']),
  "verificationNote": zod.string().nullish(),
  "isFeatured": zod.boolean(),
  "favoriteCount": zod.number().int().optional(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Update a submitted Bhandara
 */



export const UpdateBhandaraParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const updateBhandaraBodyOneNameMin = 2;
export const updateBhandaraBodyOneNameMax = 120;

export const updateBhandaraBodyOneTempleMin = 2;
export const updateBhandaraBodyOneTempleMax = 120;

export const updateBhandaraBodyOneDescriptionMax = 500;

export const updateBhandaraBodyOneLocalityMin = 2;
export const updateBhandaraBodyOneLocalityMax = 80;

export const updateBhandaraBodyOneCityMin = 2;
export const updateBhandaraBodyOneCityMax = 80;

export const updateBhandaraBodyOneAddressMin = 5;
export const updateBhandaraBodyOneAddressMax = 240;

export const updateBhandaraBodyOnePrasadMin = 2;
export const updateBhandaraBodyOnePrasadMax = 120;

export const updateBhandaraBodyOneOrganizerNameMin = 2;
export const updateBhandaraBodyOneOrganizerNameMax = 120;

export const updateBhandaraBodyOneOrganizerPhoneMax = 30;

export const updateBhandaraBodyOneLatitudeMin = -90;
export const updateBhandaraBodyOneLatitudeMax = 90;

export const updateBhandaraBodyOneLongitudeMin = -180;
export const updateBhandaraBodyOneLongitudeMax = 180;



export const UpdateBhandaraBody = zod.object({
  "name": zod.string().min(updateBhandaraBodyOneNameMin).max(updateBhandaraBodyOneNameMax),
  "temple": zod.string().min(updateBhandaraBodyOneTempleMin).max(updateBhandaraBodyOneTempleMax),
  "description": zod.string().max(updateBhandaraBodyOneDescriptionMax).optional(),
  "locality": zod.string().min(updateBhandaraBodyOneLocalityMin).max(updateBhandaraBodyOneLocalityMax),
  "city": zod.string().min(updateBhandaraBodyOneCityMin).max(updateBhandaraBodyOneCityMax),
  "address": zod.string().min(updateBhandaraBodyOneAddressMin).max(updateBhandaraBodyOneAddressMax),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string().min(updateBhandaraBodyOnePrasadMin).max(updateBhandaraBodyOnePrasadMax),
  "organizerName": zod.string().min(updateBhandaraBodyOneOrganizerNameMin).max(updateBhandaraBodyOneOrganizerNameMax),
  "organizerPhone": zod.string().max(updateBhandaraBodyOneOrganizerPhoneMax).optional(),
  "latitude": zod.number().min(updateBhandaraBodyOneLatitudeMin).max(updateBhandaraBodyOneLatitudeMax),
  "longitude": zod.number().min(updateBhandaraBodyOneLongitudeMin).max(updateBhandaraBodyOneLongitudeMax)
})

export const UpdateBhandaraResponse = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "temple": zod.string(),
  "description": zod.string().nullish(),
  "locality": zod.string(),
  "city": zod.string(),
  "address": zod.string(),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string(),
  "organizerName": zod.string().optional(),
  "organizerPhone": zod.string().nullish(),
  "latitude": zod.number(),
  "longitude": zod.number(),
  "distanceKm": zod.number().nullish(),
  "verificationStatus": zod.enum(['pending', 'approved', 'rejected']),
  "verificationNote": zod.string().nullish(),
  "isFeatured": zod.boolean(),
  "favoriteCount": zod.number().int().optional(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Save a Bhandara for a device or signed-in user
 */



export const FavoriteBhandaraParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const favoriteBhandaraBodyUserKeyMax = 160;



export const FavoriteBhandaraBody = zod.object({
  "userKey": zod.string().min(1).max(favoriteBhandaraBodyUserKeyMax)
})

export const FavoriteBhandaraResponse = zod.object({
  "favorited": zod.boolean(),
  "favoriteCount": zod.number().int()
})


/**
 * @summary Remove a saved Bhandara
 */



export const UnfavoriteBhandaraParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const unfavoriteBhandaraBodyUserKeyMax = 160;



export const UnfavoriteBhandaraBody = zod.object({
  "userKey": zod.string().min(1).max(unfavoriteBhandaraBodyUserKeyMax)
})

export const UnfavoriteBhandaraResponse = zod.object({
  "favorited": zod.boolean(),
  "favoriteCount": zod.number().int()
})


/**
 * @summary Report an incorrect, cancelled, or duplicate Bhandara
 */
export const reportBhandaraBodyNoteMax = 500;

export const reportBhandaraBodyReporterKeyMax = 160;



export const ReportBhandaraBody = zod.object({
  "bhandaraId": zod.number().int(),
  "reason": zod.enum(['incorrect', 'cancelled', 'duplicate', 'other']),
  "note": zod.string().max(reportBhandaraBodyNoteMax).optional(),
  "reporterKey": zod.string().max(reportBhandaraBodyReporterKeyMax).optional()
})

export const ReportBhandaraResponse = zod.object({
  "id": zod.number().int(),
  "bhandaraId": zod.number().int(),
  "reason": zod.string(),
  "note": zod.string().nullish(),
  "status": zod.enum(['open', 'reviewed', 'dismissed']),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get moderation summary
 */
export const GetAdminSummaryResponse = zod.object({
  "pending": zod.number().int(),
  "approvedToday": zod.number().int(),
  "upcoming": zod.number().int(),
  "reports": zod.number().int()
})


/**
 * @summary List submissions for moderation
 */
export const listAdminBhandarasQueryStatusDefault = `pending`;
export const listAdminBhandarasQueryQMax = 120;



export const ListAdminBhandarasQueryParams = zod.object({
  "status": zod.enum(['pending', 'approved', 'rejected', 'all']).default(listAdminBhandarasQueryStatusDefault),
  "q": zod.coerce.string().max(listAdminBhandarasQueryQMax).optional()
})

export const ListAdminBhandarasResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "temple": zod.string(),
  "description": zod.string().nullish(),
  "locality": zod.string(),
  "city": zod.string(),
  "address": zod.string(),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string(),
  "organizerName": zod.string().optional(),
  "organizerPhone": zod.string().nullish(),
  "latitude": zod.number(),
  "longitude": zod.number(),
  "distanceKm": zod.number().nullish(),
  "verificationStatus": zod.enum(['pending', 'approved', 'rejected']),
  "verificationNote": zod.string().nullish(),
  "isFeatured": zod.boolean(),
  "favoriteCount": zod.number().int().optional(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})),
  "total": zod.number().int()
})


/**
 * @summary Approve, edit, or reject a submission
 */



export const ModerateBhandaraParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const moderateBhandaraBodyVerificationNoteMax = 500;

export const moderateBhandaraBodyNameMax = 120;

export const moderateBhandaraBodyPrasadMax = 120;

export const moderateBhandaraBodyAddressMax = 240;



export const ModerateBhandaraBody = zod.object({
  "action": zod.enum(['approve', 'reject', 'edit']),
  "verificationNote": zod.string().max(moderateBhandaraBodyVerificationNoteMax).optional(),
  "name": zod.string().max(moderateBhandaraBodyNameMax).optional(),
  "startAt": zod.coerce.date().optional(),
  "endAt": zod.coerce.date().optional(),
  "prasad": zod.string().max(moderateBhandaraBodyPrasadMax).optional(),
  "address": zod.string().max(moderateBhandaraBodyAddressMax).optional()
})

export const ModerateBhandaraResponse = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "temple": zod.string(),
  "description": zod.string().nullish(),
  "locality": zod.string(),
  "city": zod.string(),
  "address": zod.string(),
  "startAt": zod.coerce.date(),
  "endAt": zod.coerce.date(),
  "prasad": zod.string(),
  "organizerName": zod.string().optional(),
  "organizerPhone": zod.string().nullish(),
  "latitude": zod.number(),
  "longitude": zod.number(),
  "distanceKm": zod.number().nullish(),
  "verificationStatus": zod.enum(['pending', 'approved', 'rejected']),
  "verificationNote": zod.string().nullish(),
  "isFeatured": zod.boolean(),
  "favoriteCount": zod.number().int().optional(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Delete a Bhandara
 */



export const DeleteBhandaraParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const DeleteBhandaraResponse = zod.void()


