/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type BhandaraVerificationStatus = typeof BhandaraVerificationStatus[keyof typeof BhandaraVerificationStatus];
export declare const BhandaraVerificationStatus: {
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
//# sourceMappingURL=bhandaraVerificationStatus.d.ts.map