/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Bhandara } from './bhandara';

export interface BhandaraListResponse {
  items: Bhandara[];
  total: number;
}
