/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface BhandaraInput {
  /**
     * @minLength 2
     * @maxLength 120
     */
  name: string;
  /**
     * @minLength 2
     * @maxLength 120
     */
  temple: string;
  /** @maxLength 500 */
  description?: string;
  /**
     * @minLength 2
     * @maxLength 80
     */
  locality: string;
  /**
     * @minLength 2
     * @maxLength 80
     */
  city: string;
  /**
     * @minLength 5
     * @maxLength 240
     */
  address: string;
  startAt: Date;
  endAt: Date;
  /**
     * @minLength 2
     * @maxLength 120
     */
  prasad: string;
  /**
     * @minLength 2
     * @maxLength 120
     */
  organizerName: string;
  /** @maxLength 30 */
  organizerPhone?: string;
  /**
     * @minimum -90
     * @maximum 90
     */
  latitude: number;
  /**
     * @minimum -180
     * @maximum 180
     */
  longitude: number;
}
