/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type BhandaraVerificationStatus = typeof BhandaraVerificationStatus[keyof typeof BhandaraVerificationStatus];


export const BhandaraVerificationStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;
