/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { BhandaraVerificationStatus } from './bhandaraVerificationStatus';
export interface Bhandara {
    id: number;
    name: string;
    temple: string;
    /** @nullable */
    description?: string | null;
    locality: string;
    city: string;
    address: string;
    startAt: Date;
    endAt: Date;
    prasad: string;
    organizerName?: string;
    /** @nullable */
    organizerPhone?: string | null;
    latitude: number;
    longitude: number;
    /** @nullable */
    distanceKm?: number | null;
    verificationStatus: BhandaraVerificationStatus;
    /** @nullable */
    verificationNote?: string | null;
    isFeatured: boolean;
    favoriteCount?: number;
    createdAt: Date;
    updatedAt: Date;
}
//# sourceMappingURL=bhandara.d.ts.map