/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type ListBhandarasSort = typeof ListBhandarasSort[keyof typeof ListBhandarasSort];
export declare const ListBhandarasSort: {
    readonly soonest: "soonest";
    readonly nearest: "nearest";
};
//# sourceMappingURL=listBhandarasSort.d.ts.map