/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type ListBhandarasDateFilter = typeof ListBhandarasDateFilter[keyof typeof ListBhandarasDateFilter];
export declare const ListBhandarasDateFilter: {
    readonly all: "all";
    readonly today: "today";
    readonly tomorrow: "tomorrow";
    readonly week: "week";
    readonly custom: "custom";
};
//# sourceMappingURL=listBhandarasDateFilter.d.ts.map