/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ListAdminBhandarasStatus } from './listAdminBhandarasStatus';
import type { SearchQueryParameter } from './searchQueryParameter';

export type ListAdminBhandarasParams = {
status?: ListAdminBhandarasStatus;
/**
 * @maxLength 120
 */
q?: SearchQueryParameter;
};
