/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type ListAdminBhandarasStatus = typeof ListAdminBhandarasStatus[keyof typeof ListAdminBhandarasStatus];
export declare const ListAdminBhandarasStatus: {
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
    readonly all: "all";
};
//# sourceMappingURL=listAdminBhandarasStatus.d.ts.map