/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ListAdminBhandarasStatus = typeof ListAdminBhandarasStatus[keyof typeof ListAdminBhandarasStatus];


export const ListAdminBhandarasStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
  all: 'all',
} as const;
