/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { CityQueryParameter } from './cityQueryParameter';
import type { ListBhandarasDateFilter } from './listBhandarasDateFilter';
import type { ListBhandarasSort } from './listBhandarasSort';
import type { LocalityQueryParameter } from './localityQueryParameter';
import type { SearchQueryParameter } from './searchQueryParameter';

export type ListBhandarasParams = {
/**
 * @maxLength 120
 */
q?: SearchQueryParameter;
/**
 * @maxLength 80
 */
city?: CityQueryParameter;
/**
 * @maxLength 80
 */
locality?: LocalityQueryParameter;
dateFilter?: ListBhandarasDateFilter;
/**
 * @nullable
 */
date?: Date | null;
/**
 * @minimum 1
 * @maximum 200
 * @nullable
 */
maxDistanceKm?: number | null;
/**
 * @minimum -90
 * @maximum 90
 * @nullable
 */
latitude?: number | null;
/**
 * @minimum -180
 * @maximum 180
 * @nullable
 */
longitude?: number | null;
sort?: ListBhandarasSort;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
