/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ListBhandarasSort = typeof ListBhandarasSort[keyof typeof ListBhandarasSort];


export const ListBhandarasSort = {
  soonest: 'soonest',
  nearest: 'nearest',
} as const;
