/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ListBhandarasDateFilter = typeof ListBhandarasDateFilter[keyof typeof ListBhandarasDateFilter];


export const ListBhandarasDateFilter = {
  all: 'all',
  today: 'today',
  tomorrow: 'tomorrow',
  week: 'week',
  custom: 'custom',
} as const;
