/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ModerationInputAction = typeof ModerationInputAction[keyof typeof ModerationInputAction];


export const ModerationInputAction = {
  approve: 'approve',
  reject: 'reject',
  edit: 'edit',
} as const;
