/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ModerationInputAction } from './moderationInputAction';

export interface ModerationInput {
  action: ModerationInputAction;
  /** @maxLength 500 */
  verificationNote?: string;
  /** @maxLength 120 */
  name?: string;
  startAt?: Date;
  endAt?: Date;
  /** @maxLength 120 */
  prasad?: string;
  /** @maxLength 240 */
  address?: string;
}
