/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type ReportInputReason = typeof ReportInputReason[keyof typeof ReportInputReason];


export const ReportInputReason = {
  incorrect: 'incorrect',
  cancelled: 'cancelled',
  duplicate: 'duplicate',
  other: 'other',
} as const;
