/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ReportStatus } from './reportStatus';

export interface Report {
  id: number;
  bhandaraId: number;
  reason: string;
  /** @nullable */
  note?: string | null;
  status: ReportStatus;
  createdAt: Date;
}
