/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ReportInputReason } from './reportInputReason';

export interface ReportInput {
  bhandaraId: number;
  reason: ReportInputReason;
  /** @maxLength 500 */
  note?: string;
  /** @maxLength 160 */
  reporterKey?: string;
}
